### ISSUE TITLE
 filename = ffi.new('char[]', name.encode())

### ISSUE THREAD

**Issue by hydronics2** [bastibe/WebGL-Spectrogram#7]
I've been getting the following error... any help? thank you, thomas

ERROR:tornado.application:Uncaught exception in /spectrogram
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 369, in _run_callback
    callback(*args, **kwargs)
  File "server.py", line 101, in on_message
    self.receive_message(header['type'], header['content'], data)
  File "server.py", line 154, in receive_message
    self.on_data_spectrogram(data, **content)
  File "server.py", line 196, in on_data_spectrogram
    file = SoundFile(io.BytesIO(data))
  File "/usr/local/lib/python2.7/dist-packages/pysoundfile.py", line 293, in __init__
    filename = ffi.new('char[]', name.encode())
AttributeError: '_io.BytesIO' object has no attribute 'encode'
Exception AttributeError: AttributeError('SoundFile has no attribute _file',) in <bound method SoundFile.__del__ of <pysoundfile.SoundFile object at 0x7f2b5ccdf590>> ignored
WebSocket closed

**Comment by bastibe** [comment]
Please use Python 3.
